Category.create(:name => "Apartments")
Category.create(:name => "Cars for Sale")
Category.create(:name => "Sexual Healing")
Category.create(:name => "Jobs")
Post.create(:title => "Nob hill apartment", :price => 499.99, :body => "asdfjlas;lfdksdl;kafjalksjfsdaf", :email => "cdizzle@gmail.com", :contact_name => "Brooks aka bdizzle", :category_id => 0)
Post.create(:title => "Nob hill apartment", :price => 499.99, :body => "asdfjlas;lfdksdl;kafjalksjfsdaf", :email => "cdizzle@gmail.com", :contact_name => "Brooks aka bdizzle", :category_id => 1)
Post.create(:title => "Nob hill apartment", :price => 499.99, :body => "asdfjlas;lfdksdl;kafjalksjfsdaf", :email => "cdizzle@gmail.com", :contact_name => "Brooks aka bdizzle", :category_id => 2)
Post.create(:title => "Nob hill apartment", :price => 499.99, :body => "asdfjlas;lfdksdl;kafjalksjfsdaf", :email => "cdizzle@gmail.com", :contact_name => "Brooks aka bdizzle", :category_id => 3)
